# .goreleaser.yml
# Build customization
builds:
  - binary: s3-cli 
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64

# Archive customization
archive:
  format: tgz
  replacements:
    386: 32-bit
    amd64: 64-bit

    darwin: macOS